# The URL the site will be built for
base_url = "https://jack.wrenn.fyi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate feeds.
generate_feeds = true

taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
]

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "github-light"


[extra]
# Put all your custom variables here
